spring:
  rabbitmq:
    host: 81.71.96.88
    port: 5672
    username: ark
    password: alice
    virtual-host: gundam
    connection-timeout: 60000
  data:
    redis:
      host: 81.71.96.88  # 新配置路径
      port: 6379
      password: X1234567
      database: 0
      client-type: jedis # 可选：强制使用Jedis
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 2000ms
      connect-timeout: 2000ms
      timeout: 1000ms

    mongodb:
      uri: mongodb://root:pcb1234@81.71.96.88:27017/logistics-db?authSource=admin

logging:
  file:
    name: logs/myapp.log
  level:
    com.work.logistics: INFO
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
